### ISSUE TITLE
pycargoebuild creates new ebuilds with -rw------- permissions

### ISSUE THREAD

**Issue by juippis** [projg2/pycargoebuild#12]
... so when copy-pasting them to a git tree to be ran, portage errors out with:
```
/usr/lib/portage/python3.10/ebuild.sh: line 628: /var/db/repos/gentoo/media-sound/ncspot/ncspot-0.12.0.ebuild: Permission denied
 * ERROR: media-sound/ncspot-0.12.0::gentoo failed (depend phase):
 *   error sourcing ebuild
```

-rw-r--r-- (or 0644) is enough for it to work.

**Comment by mgorny** [comment]
Right. It's using `tempfile.NamedTemporaryFile`, so it defaults to safe permissions. I'll change that.

**Comment by juippis** [comment]
Thank you!
