### ISSUE TITLE
handle GIT_CRATES

### ISSUE THREAD

**Issue by gyakovlev** [projg2/pycargoebuild#15]
cargo.eclass got an ability to generically handle git crates

https://github.com/gentoo/gentoo/commit/49a81668b60c1d54885e62b000595141ee6ff333
https://github.com/gentoo/cargo-ebuild/issues/33

pycargoebuild could leverage it.
this is not a very common scenario, still useful nonetheless.

possible test subject:
dev-util/rustup (non live versions ofc)
https://github.com/gentoo/gentoo/blob/master/dev-util/rustup/rustup-1.25.2.ebuild

**Comment by Schievel1** [comment]
Alternatively for the time being it would be beneficial if pycargoebuild would just ignore the git crate and maybe spit out a warning that it skipped it. 
Similar to what `cargo ebuild` does. I can then add the git crates manually. 

Right now it does this:
```
➜ pycargoebuild ./
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/pycargoebuild", line 8, in <module>
    sys.exit(entry_point())
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pycargoebuild/__main__.py", line 212, in entry_point
    sys.exit(main(*sys.argv))
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pycargoebuild/__main__.py", line 123, in main
    crates.update(get_crates(f))
  File "/usr/lib/python3.11/site-packages/pycargoebuild/cargo.py", line 65, in get_crates
    raise RuntimeError(f"Unsupported crate source: {p['source']}")
RuntimeError: Unsupported crate source: git+https://github.com/an-anime-team/anime-game-core?tag=1.13.1#e8b99564f4ea12a331aa276ea91fe65c0ead465e
```

Program I want to package is this:
https://github.com/an-anime-team/the-honkers-railway-launcher

**Comment by mgorny** [comment]
Also, how to get `crate_dir`? Do I have to parse `Cargo.toml` to find the respective module in the fetched distfile?

**Comment by CyberTailor** [comment]
> Also, how to get crate_dir? 

Unpack and match every Cargo.toml against package name. Cargo.lock doesn't provide paths :(

**Comment by mgorny** [comment]
Yes, I was thinking about that too. However, is that what cargo actually does? I somewhat suspect it looks at top-level `Cargo.toml` instead, and either that's the package we want, or a workspace with package we want.
