### ISSUE TITLE
Output SRC_URI with package source

### ISSUE THREAD

**Issue by Tatsh** [projg2/pycargoebuild#28]
Currently `SRC_URI` is generated to only have `CARGO_CRATE_URIS`:

```shell
SRC_URI="
        ${CARGO_CRATE_URIS}
"
```

It needs to have the main source of the package:

```shell
SRC_URI="
        https://github.com/YS-L/${PN}/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
        ${CARGO_CRATE_URIS}
"
```

It would be interesting to have an option like `--github` that would be used like so: `--github YS-L/csvlens` so the above URI can be added.

**Comment by mgorny** [comment]
There's really no point in having a special option to add every possible line that could be written into the ebuild. `pycargoebuild` is just a template generator, and you fill that template it in afterwards. Then you use `-i` to update the ebuild for new versions without having to change anything else.
