### ISSUE TITLE
pycargoebuild can't handle rust-bindgen workspaces or relative-paths

### ISSUE THREAD

**Issue by srcshelton** [projg2/pycargoebuild#9]
When using both the Gentoo `pycargoebuild` ebuild for release 0.5.2 and an upgraded copy for release 0.5.3, I get the following error (when run against https://github.com/rust-lang/rust-bindgen.git `v0.63.0`):

```
sh-5.1# pycargoebuild .
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/pycargoebuild", line 8, in <module>
    sys.exit(entry_point())
  File "/root/.local/lib/python3.10/site-packages/pycargoebuild/__main__.py", line 202, in entry_point
    sys.exit(main(*sys.argv))
  File "/root/.local/lib/python3.10/site-packages/pycargoebuild/__main__.py", line 97, in main
    pkg_metas.append(get_package_metadata(f))
  File "/root/.local/lib/python3.10/site-packages/pycargoebuild/cargo.py", line 77, in get_package_metadata
    pkg_meta = cargo_toml["package"]
KeyError: 'package'
```

… and now I look, `rust-bindgen`'s top-level Cargo.toml contains:

```
[workspace]
members = [
    "bindgen",
    "bindgen-cli",
    "bindgen-integration",
    "bindgen-tests",
    "bindgen-tests/tests/quickchecking",
    "bindgen-tests/tests/expectations",
]

default-members = [
    "bindgen",
    "bindgen-cli",
    "bindgen-tests",
]
```

… with no `package` section defined.

Having said this, re-running from the `bindgen` subdirectory also fails, with:

```
sh-5.1# pycargoebuild .
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/pycargoebuild/cargo.py", line 64, in crate_from_cargo_lock
    checksum=p["checksum"])
KeyError: 'checksum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/pycargoebuild", line 8, in <module>
    sys.exit(entry_point())
  File "/root/.local/lib/python3.10/site-packages/pycargoebuild/__main__.py", line 202, in entry_point
    sys.exit(main(*sys.argv))
  File "/root/.local/lib/python3.10/site-packages/pycargoebuild/__main__.py", line 100, in main
    crates.update(get_crates(f, exclude=exclude))
  File "/root/.local/lib/python3.10/site-packages/pycargoebuild/cargo.py", line 69, in <genexpr>
    return (crate_from_cargo_lock(p)
  File "/root/.local/lib/python3.10/site-packages/pycargoebuild/cargo.py", line 66, in crate_from_cargo_lock
    raise RuntimeError("Incorrect/insufficient metadata for crate: "
RuntimeError: Incorrect/insufficient metadata for crate: {'name': 'bindgen-cli', 'version': '0.63.0', 'dependencies': ['bindgen', 'clap 3.2.12', 'env_logger 0.9.0', 'log 0.4.14', 'shlex']}
```

… whereas attempting the same against `bindgen-cli` fails with:

```
RuntimeError: Incorrect/insufficient metadata for crate: {'name': 'bindgen', 'version': '0.63.0', 'dependencies': ['bitflags', 'cexpr', 'clang-sys', 'lazy_static', 'lazycell', 'log 0.4.14', 'peeking_take_while', 'proc-macro2', 'quote', 'regex 1.5.5', 'rustc-hash', 'shlex', 'syn', 'which']}
```

Noting that `Cargo.toml` references `bindgen` as:

```
bindgen = { path = "../bindgen", version = "=0.63.0" }
```

**Comment by mgorny** [comment]
CC @arkamar who added workspace support.

**Comment by mgorny** [comment]
BTW if you could provide a rough example how an example ebuild for this should look like, or how it should be constructed, it'd definitely be helpful.

**Comment by arkamar** [comment]
I am not sure if it makes sense for `pycargoebuild` to support call in root of the `rust-bindgen` repository, because `members` lead to multiple directories where each of them contains `Cargo.toml` with a `[package]` section.

Anyway, the second and third example, which we should fix, fails when `Cargo.lock` is processed, because `bindgen` and `bindgen-cli` are missing `checksum` field. They should have been excluded from the crate list, because they are workspace members, but we are not processing parent `Cargo.toml` file(s) currently, therefore we missed that information. In order to fix this issue, we need to extract workspace members from all parent `Cargo.toml` files and append them to `exclude` list.

**Comment by mgorny** [comment]
But where does the ebuild/eclass operate? Does it operate on the top directory of the workspace?

**Comment by mgorny** [comment]
Ok, I've given it some more thinking and was almost sure I've figured it out. Then it occurred to me that the current approach will capture all packages in `Cargo.lock`. I suppose it's acceptable for now. However, I suppose eventually we'd want the user to explicitly specify which of the subpackages they need, and process only depgraph of these packages.

**Comment by mgorny** [comment]
More notes:
- we currently take `workspace.members` as list of package names — we ought to be treating them as directory list, and read names from `Cargo.toml` files there
- Cargo docs say that dependencies with `path` automatically become workspace members, perhaps we should implement that as well
- and/or we should probably read `workspace` from `Cargo.toml` alongside `Cargo.lock`
